spring.application.name=MovieApi
spring.datasource.url=jdbc:Mysql://localhost:3306/movieapi?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=dinesh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
project.posters=poster/
base.Url=http://localhost:8080


